pyms:
  services:
    swagger:
      path: ""
      file: "swagger.yaml"
      url: "ws-doc/"
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Python Microservice Swagger"
    APPLICATION_ROOT: "/"